#!/bin/bash
~/workspace/jif3D/Joint/bin/gcc-5.4.0/release/parallelization-openmp/threading-multi/jointinv  --crossgrad --writerays --substart True --curvreg --scalrelerr 0 --scalminerr 5e-7 --ftgminerr 1e-9 --pickerr 0.02 --mindens 0.0 -- maxdens 5.0 << eof
start_tomo.nc
1
start_tomo.nc
tomo_ano.nc.tt.nc
1
1
dens_ano.nc.sgd.nc
dens_ano.nc.ftg.nc
start_dens.nc
0
1e5
0
0
100
100
0
100
eof

