#!/bin/bash
find -wholename *gcc-4.4.3*release*.so -exec cp '{}' ~/jiba_dist \;
cp ~/workspace/jiba++/Joint/bin/gcc-4.4.3/release/threading-multi/jointinv ~/jiba_dist
cp ~/workspace/jiba++/Tomo/bin/gcc-4.4.3/release/threading-multi/tomogrid ~/jiba_dist
cp ~/workspace/jiba++/Hacks/bin/gcc-4.4.3/release/threading-multi/mtinv ~/jiba_dist

chrpath -r /home/mmoorkamp/jiba_dist ~/jiba_dist/jointinv
chrpath -r /home/mmoorkamp/jiba_dist ~/jiba_dist/tomogrid
chrpath -r /home/mmoorkamp/jiba_dist ~/jiba_dist/mtinv
