#!/bin/bash
#prepare all files for release to another system
#collect all source files and build files
find -name "*.h" > distfiles
find -name "*.hpp" >> distfiles
find -name "*.cpp" >> distfiles
find -name "*.cu" >> distfiles
find -name "Jam*" >> distfiles
find -name "*.jam" >> distfiles
find -name "*.for" >> distfiles
echo "README" >> distfiles
find -name "Doxyfile.*" >> distfiles
#create a tar archive with the files listed above
tar cf jiba.tar -T distfiles 
