#!/bin/bash

rm *.nc 
#generate a seismic mesh with 20x20x10 cells
#each cell will be 500mx500mx500m and the velocity
#will change from 3000m/s at the top to 6000m/s at
#the bottom of the domain
#the output file name is  start_tomo.nc
../../Tomo/bin/gcc-4.8/release/parallelization-openmp/threading-multi/makeseismesh << eof
20
20
10
500
3000
6000
start_tomo.nc
eof

#create an anomaly
# we generate a high velocity and a low velocity anomaly in the
#upper 4 layers (index 0-3) in the centre of the model
# the output filename is tomo_ano.nc
#this file can be viewed with ncview (http://meteora.ucsd.edu/~pierce/ncview_home_page.html)
#, for example
ncap2 -s "Slowness(0:3,5:10,5:15)=Slowness(0:3,5:10,5:15)*1.2; Slowness(0:3,11:15,5:15)=Slowness(0:3,11:15,5:15)/1.2" start_tomo.nc tomo_ano.nc


#calculate synthetic data first arrival data
#sources and receivers will be placed at the surface between 1000m and 9000m
#with a 2000m spacing between them
#we are adding 2% gaussian noise to the data
../../Tomo/bin/gcc-4.8/release/parallelization-openmp/threading-multi/tomogrid << eof
1000
9000
2000
1000
9000
2000
0
1000
9000
2000
1000
9000
2000
0
tomo_ano.nc
0.02
eof

#create density model using the relationship
# rho = (v+8500)/5000 where v is velocity and rho is density
ncap2 -s "Density=1.0/5000.0*(1.0/Slowness+8500)" tomo_ano.nc dens_ano.nc
ncap2 -s "Density=1.0/5000.0*(1.0/Slowness+8500)" start_tomo.nc start_dens.nc
#the joint inversion code checks for correct units
#so we have to change the unit string according to udunit conventions
ncatted -O -a units,Density,m,c,"g/cm3" dens_ano.nc
ncatted -O -a units,Density,m,c,"g/cm3" start_dens.nc
#create the background around the gridded domain
#we embedd the density model in a layered background to avoid
#boundary effects fromt the finite extent of the grid
ncap2 -A -S makedens dens_ano.nc
ncap2 -A -S makedens start_dens.nc

ncap2 -A -s "Density(0:3,5:15,10:15) = 3.0" dens_ano.nc
#calculate synthetic scalar and tensor gravity data
#the measurements are located between 1400m and 8400m
#in x-direction and y-direction with a spacing of 500m
#we do not add any noise to the data 
../../Gravity/bin/gcc-4.8/release/parallelization-openmp/threading-multi/gravgrid << eof
1400
8400
500
1400
8400
500
0
dens_ano.nc
0.0
0.0
0
0
eof


#create a conductivity model 
#we currently do not use the conductivity model
ncap2 -s "Conductivity = exp(-(2.31e-7/Slowness^2-5.79e-4/Slowness+0.124))" tomo_ano.nc cond_ano.nc
ncatted -O -a units,Conductivity,m,c,"S/m" cond_ano.nc


